name: local_notification_app_demo
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.2
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.9
  http: ^1.1.2
  path_provider: ^2.1.1
  supabase: ^1.11.11
  supabase_flutter: ^1.10.25
  uuid: ^4.2.1
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 500
  uses-material-design: true
  assets:
    - assets/images/illustration.svg
    - assets/images/logo.svg
    - assets/images/no_data.svg
    - .env
